bot_name: options-bot                     # define Docker image name and bot deploy path
paper_trading: true                       # Alpaca paper trading (true) or live trading (false)

ticker: AAPL                              # ticker to trade options on
call_option_margin: 0.05                  # relative margin for covered calls
put_option_margin: 0.05                   # relative margin for covered puts

timezone: America/New_York                # schedule timezone (IANA format)
trade_options_schedule: "59 9 * * 1-5"    # 09:59 AM weekdays
check_value_schedule: "0 10-16 * * 1-5"   # every hour 10:00--16:00 weekdays
